apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: crunchy-bridge-operator-dbaasprovider-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviders/status
  verbs:
  - get
