# permissions for end users to view bridgeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgecluster-viewer-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters/status
  verbs:
  - get
