# permissions for end users to edit bridgeservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgeservice-editor-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeservices/status
  verbs:
  - get
