# permissions for end users to edit bridgeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgecluster-editor-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters/status
  verbs:
  - get
