# permissions for end users to view bridgeservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgeservice-viewer-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeservices/status
  verbs:
  - get
