# permissions for end users to edit crunchybridgeinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchybridgeinventory-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories/status
  verbs:
  - get
