# permissions for end users to view crunchybridgeinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchybridgeinventory-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories/status
  verbs:
  - get
