# permissions for end users to view crunchybridgeconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchybridgeconnection-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeconnections/status
  verbs:
  - get
