# permissions for end users to view crunchybridgeinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchybridgeinstance-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinstances/status
  verbs:
  - get
