# permissions for end users to edit databaseroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaserole-editor-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - databaseroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - databaseroles/status
  verbs:
  - get
