# permissions for end users to view databaseroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaserole-viewer-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - databaseroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - databaseroles/status
  verbs:
  - get
