# permissions for end users to view dbaasproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasprovider-viewer-role
rules:
  - apiGroups:
      - dbaas.redhat.com
    resources:
      - dbaasproviders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dbaas.redhat.com
    resources:
      - dbaasproviders/status
    verbs:
      - get
