
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters/finalizers
  verbs:
  - update
- apiGroups:
  - crunchybridge.crunchydata.com
  resources:
  - bridgeclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeconnections/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crunchybridgeinventories/status
  verbs:
  - get
  - patch
  - update
