apiVersion: crunchybridge.crunchydata.com/v1alpha1
kind: BridgeCluster
metadata:
  name: bridgecluster-sample
spec:
  name: TestCluster
  plan: hobby-2
  storage: 10
  provider: aws
  region: us-east-1
  pg_major_version: 12

