// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeConnection) DeepCopyInto(out *CrunchyBridgeConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeConnection.
func (in *CrunchyBridgeConnection) DeepCopy() *CrunchyBridgeConnection {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrunchyBridgeConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeConnectionList) DeepCopyInto(out *CrunchyBridgeConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CrunchyBridgeConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeConnectionList.
func (in *CrunchyBridgeConnectionList) DeepCopy() *CrunchyBridgeConnectionList {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrunchyBridgeConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeConnectionSpec) DeepCopyInto(out *CrunchyBridgeConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeConnectionSpec.
func (in *CrunchyBridgeConnectionSpec) DeepCopy() *CrunchyBridgeConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeConnectionStatus) DeepCopyInto(out *CrunchyBridgeConnectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeConnectionStatus.
func (in *CrunchyBridgeConnectionStatus) DeepCopy() *CrunchyBridgeConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeInventory) DeepCopyInto(out *CrunchyBridgeInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeInventory.
func (in *CrunchyBridgeInventory) DeepCopy() *CrunchyBridgeInventory {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrunchyBridgeInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeInventoryList) DeepCopyInto(out *CrunchyBridgeInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CrunchyBridgeInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeInventoryList.
func (in *CrunchyBridgeInventoryList) DeepCopy() *CrunchyBridgeInventoryList {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrunchyBridgeInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeInventorySpec) DeepCopyInto(out *CrunchyBridgeInventorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeInventorySpec.
func (in *CrunchyBridgeInventorySpec) DeepCopy() *CrunchyBridgeInventorySpec {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrunchyBridgeInventoryStatus) DeepCopyInto(out *CrunchyBridgeInventoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrunchyBridgeInventoryStatus.
func (in *CrunchyBridgeInventoryStatus) DeepCopy() *CrunchyBridgeInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(CrunchyBridgeInventoryStatus)
	in.DeepCopyInto(out)
	return out
}
